class PCCS {
  static const List<String> items = [
    '1a Control a day FW CAS mission with non-precision ordnance. Live or Dry (one may be simulated)',
    '1b Control a day FW CAS mission with non-precision ordnance.',
    '2a Control a day RW CAS mission with non-precision ordnance. Live or Dry (one may be simulated)',
    '2b Control a day RW CAS mission with non-precision ordnance.',
    '3a Control a night FW or RW CAS mission with non-precision ordnance. Live or Dry (one may be simulated)',
    '3b Control a night FW or RW CAS mission with non-precision ordnance.',
    '4a Control a night CAS mission on a target marked by IR. Live or Dry (one may be simulated)',
    '4b Control a night CAS mission on a target marked by IR.',
    '5a Control delivery of FW laser-guided weapons on a target marked by a ground-based laser. Live or Dry (one may be simulated)',
    '5b Control delivery of FW laser-guided weapons on a target marked by a ground-based laser.',
    '6 Control delivery of RW laser-guided weapons.',
    '7a Control FW or RW aircraft attacks using type 3 terminal attack control. Live or Dry (one may be simulated)',
    '7b Control FW or RW aircraft attacks using type 3 terminal attack control.',
    '8a Employ a remote observer during type 2 or 3 terminal attack control. May be simulated',
    '8b Employ a remote observer during type 2 or 3 terminal attack control.',
    '9a Conduct target area correlation using video downlink. May be simulated',
    '9b Conduct target area correlation using video downlink.',
    '10 Control a day urban CAS mission with a section of CAS aircraft.',
    '11 Control a night urban CAS mission with a section of CAS aircraft.',
    '12a Integrate FW CAS attacks with live indirect fires in a non-permissive environment.',
    '12b Integrate FW CAS attacks with live indirect fires in a non-permissive environment.',
    '13 Integrate RW CAS attacks with indirect fire in a non-permissive environment.',
    '14a Integrate FW CAS attacks with ground manoeuvre. Live or Dry (one may be simulated)',
    '14b Integrate FW CAS attacks with ground manoeuvre.',
    '15 Integrate RW CAS attacks with ground manoeuvre.',
    '16a Integrate UAS with CAS.',
    '16b Integrate UAS with CAS.',
    '17 Conduct FAC(A) integration.',
    '18a Conduct Type 1 terminal attack control using reversionary techniques. Live or Dry (one may be simulated)',
    '18b Conduct Type 1 terminal attack control using reversionary techniques.',
    '19a Conduct ASIMS Reporter Training.',
    '19b Conduct a practical demonstration of how to initiate a DASOR.',
    'L1 CAS',
    'L2 CAS with Pairs of A/C',
    'L3 US Procedures',
    'L4 Aircraft & Weapons',
    'L5 Maps & Datums / Weapons Effects',
    'E1 Harris 117 / 167 Radio',
    'E2 Harris 152 / 163 Radio',
    'E3 FIRESTORM',
    'E4 PMS',
    'E5 Ground LTD',
    'E6 DAGR',
    'E7 IZLID',
    'E8 JCRVT',
  ];
}